import os
import json
import hashlib
import datetime
from fastapi import APIRouter
from fastapi.responses import FileResponse
from pydantic import BaseModel
from typing import Any, Dict, Optional

from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

router = APIRouter()

REPORTS_DIR = os.path.join(os.path.dirname(__file__), "reports")
os.makedirs(REPORTS_DIR, exist_ok=True)
DATABASE_URL = os.getenv("DATABASE_URL", "postgresql://postgres:postgres@localhost:5432/governance")

BRAND = RGBColor(0x1F, 0x3A, 0x5F)
ACCENT = RGBColor(0x2E, 0x6B, 0x9E)
GREY = RGBColor(0x60, 0x60, 0x60)
DECISION_COLOUR = {"approve": RGBColor(0x1B, 0x7F, 0x37), "deny": RGBColor(0xB3, 0x26, 0x1E),
                   "human_review": RGBColor(0xB5, 0x71, 0x00)}
DECISION_LABEL = {"approve": "APPROVED", "deny": "DENIED",
                  "human_review": "ESCALATED - HUMAN REVIEW REQUIRED"}
OBLIGATION = {
    "Article 5": ("EU AI Act", "Prohibited AI practices (unacceptable-risk uses)."),
    "Article 6": ("EU AI Act", "Classification rules for high-risk AI systems."),
    "Article 9": ("EU AI Act", "Risk management system for high-risk AI."),
    "Article 10": ("EU AI Act", "Data and data governance obligations."),
    "Article 12": ("EU AI Act", "Record-keeping and automatic event logging."),
    "Article 13": ("EU AI Act", "Transparency and provision of information to deployers."),
    "Article 14": ("EU AI Act", "Human oversight of high-risk AI systems."),
    "Article 15": ("EU AI Act", "Accuracy, robustness and cybersecurity."),
    "Article 50": ("EU AI Act", "Transparency obligations towards natural persons."),
    "Article 22": ("GDPR", "Right not to be subject to solely automated decisions."),
    "Article 25": ("GDPR", "Data protection by design and by default."),
    "Article 32": ("GDPR", "Security of processing."),
    "Article 35": ("GDPR", "Data protection impact assessment."),
}
CHECK_META = {
    "compliance": ("Regulatory Compliance", "EU AI Act Art. 9-15 / GDPR Art. 5"),
    "security": ("Security & Integrity", "EU AI Act Art. 15"),
    "privacy": ("Data Privacy", "GDPR Art. 5, 9, 32"),
    "permission": ("Authorisation & Oversight", "EU AI Act Art. 14"),
}


class GatewayPayload(BaseModel):
    record: Dict[str, Any]
    explanation: Optional[str] = ""


def _shade(cell, hex_colour):
    tcPr = cell._tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:fill"), hex_colour)
    tcPr.append(shd)


def _set_cell(cell, text, bold=False, colour=None, size=10):
    cell.text = ""
    r = cell.paragraphs[0].add_run(str(text))
    r.bold = bold
    r.font.size = Pt(size)
    if colour:
        r.font.color.rgb = colour


def _kv_table(doc, rows):
    t = doc.add_table(rows=0, cols=2)
    t.style = "Table Grid"
    t.alignment = WD_TABLE_ALIGNMENT.LEFT
    for k, v in rows:
        cells = t.add_row().cells
        _set_cell(cells[0], k, bold=True)
        _shade(cells[0], "EAF0F6")
        _set_cell(cells[1], v)
    cells[0].width = Inches(2.4)
    return t


def _heading(doc, text, n=1):
    h = doc.add_heading(text, level=n)
    for run in h.runs:
        run.font.color.rgb = BRAND if n == 1 else ACCENT
    return h


def _footer_pagenum(doc, report_id):
    p = doc.sections[0].footer.paragraphs[0]
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run("CONFIDENTIAL - INTERNAL GOVERNANCE RECORD   |   " + report_id + "   |   Page ")
    run.font.size = Pt(8)
    run.font.color.rgb = GREY
    fld = OxmlElement("w:fldSimple")
    fld.set(qn("w:instr"), "PAGE")
    r = OxmlElement("w:r")
    r.append(OxmlElement("w:rPr"))
    fld.append(r)
    p._p.append(fld)


def build_report(rec, explanation, path):
    decision = str(rec.get("decision", "unknown"))
    now = datetime.datetime.now(datetime.timezone.utc)
    digest = hashlib.sha256(json.dumps(rec, sort_keys=True, default=str).encode()).hexdigest()[:16]
    report_id = "GOV-" + now.strftime("%Y%m%d") + "-" + digest[:6].upper()

    doc = Document()
    doc.styles["Normal"].font.name = "Calibri"
    doc.styles["Normal"].font.size = Pt(10.5)

    t = doc.add_paragraph(); t.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = t.add_run("AI GOVERNANCE DECISION REPORT"); r.bold = True; r.font.size = Pt(22); r.font.color.rgb = BRAND
    sub = doc.add_paragraph(); sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sr = sub.add_run("Automated pre-execution assessment - generated by the Governance Gateway with no manual intervention")
    sr.italic = True; sr.font.size = Pt(9); sr.font.color.rgb = GREY

    pr = doc.add_paragraph()
    pbdr = OxmlElement("w:pBdr"); bottom = OxmlElement("w:bottom")
    bottom.set(qn("w:val"), "single"); bottom.set(qn("w:sz"), "12"); bottom.set(qn("w:color"), "1F3A5F")
    pbdr.append(bottom); pr._p.get_or_add_pPr().append(pbdr)

    _kv_table(doc, [
        ("Report ID", report_id),
        ("Classification", "Confidential - Internal"),
        ("Generated (UTC)", now.strftime("%Y-%m-%d %H:%M:%S")),
        ("Generated by", "Governance Gateway v1.0 (automated)"),
        ("Assessment frameworks", "EU AI Act | GDPR | ISO/IEC 42001 | NIST AI RMF"),
        ("Record integrity (SHA-256)", digest),
    ])

    doc.add_paragraph()
    p = doc.add_paragraph()
    run = p.add_run("DECISION:  " + DECISION_LABEL.get(decision, decision.upper()))
    run.bold = True; run.font.size = Pt(15); run.font.color.rgb = DECISION_COLOUR.get(decision, RGBColor(0, 0, 0))

    _heading(doc, "1.  Executive Summary", 1)
    tier = rec.get("risk_tier", "n/a"); score = rec.get("risk_score", "n/a")
    verdict = {"approve": "approved for execution", "deny": "denied and must not proceed",
               "human_review": "escalated for mandatory human review before it may proceed"}.get(decision, "assessed")
    doc.add_paragraph(
        "The Governance Gateway assessed a request by agent '" + str(rec.get("agent_id","?")) + "' to perform the action '"
        + str(rec.get("action","the requested action")) + "' on behalf of user '" + str(rec.get("user_id","?"))
        + "'. Following automated intent analysis, risk classification, regulatory retrieval and four control checks, the "
        + "request has been " + verdict + ". The assessed residual risk is " + str(score) + "/100 (" + str(tier)
        + " tier). This report constitutes the auditable compliance record for that decision and is retained in "
        + "accordance with record-keeping obligations under EU AI Act Article 12.")

    _heading(doc, "2.  Request Under Assessment", 1)
    _kv_table(doc, [
        ("Agent", rec.get("agent_id", "-")), ("User", rec.get("user_id", "-")),
        ("Requested action", rec.get("action", "-")), ("Tool invoked", rec.get("tool") or "none"),
        ("Model confidence", rec.get("confidence", "-")),
        ("AI disclosed to user", "Yes" if rec.get("disclosed") else "No"),
        ("Human-in-the-loop", "Yes" if rec.get("human_in_loop") else "No"),
        ("Classified intent", rec.get("intent", "-")), ("Category", rec.get("category", "-")),
        ("Stated purpose", rec.get("purpose", "-")),
    ])
    doc.add_paragraph()
    ip = doc.add_paragraph(); ip.add_run("Original request text:  ").bold = True
    ip.add_run("\u201c" + str(rec.get("request","-")) + "\u201d").italic = True

    _heading(doc, "3.  Risk Assessment", 1)
    doc.add_paragraph(
        "The request was scored " + str(score) + "/100 and classified as " + str(tier) + "-risk under the EU AI Act risk "
        + "tiering model (unacceptable / high / limited / minimal). Scoring combines the intent category, the impact of "
        + "the requested action, and model confidence.")
    detail = rec.get("check_detail", {}) or {}
    if detail.get("risk_reasons"):
        doc.add_paragraph("Contributing factors:", style="Intense Quote")
        for rr in detail["risk_reasons"]:
            doc.add_paragraph(str(rr), style="List Bullet")

    _heading(doc, "4.  Control Checks", 1)
    doc.add_paragraph(
        "Four independent controls were evaluated. Deterministic controls apply fixed rules; the compliance control is "
        + "grounded in retrieved regulatory obligations.")
    ct = doc.add_table(rows=1, cols=4); ct.style = "Table Grid"
    for i, h in enumerate(["Control", "Result", "Mapped obligation", "Evidence / detail"]):
        _set_cell(ct.rows[0].cells[i], h, bold=True, colour=RGBColor(0xFF, 0xFF, 0xFF)); _shade(ct.rows[0].cells[i], "1F3A5F")
    checks = rec.get("checks", {}) or {}
    evidence = {
        "compliance": detail.get("compliance_reasoning", ""),
        "security": "; ".join(detail.get("security_flags", []) or []) or "No security flags raised.",
        "privacy": (", ".join(str(k) + ": " + str(v) for k, v in (detail.get("pii_found", {}) or {}).items()) or "No personal data detected."),
        "permission": "; ".join(detail.get("permission_reasons", []) or []) or "Authorisation satisfied.",
    }
    for key in ["compliance", "security", "privacy", "permission"]:
        passed = checks.get(key)
        cells = ct.add_row().cells
        _set_cell(cells[0], CHECK_META[key][0], bold=True)
        _set_cell(cells[1], "PASS" if passed else "FAIL",
                  colour=RGBColor(0x1B, 0x7F, 0x37) if passed else RGBColor(0xB3, 0x26, 0x1E), bold=True)
        _set_cell(cells[2], CHECK_META[key][1])
        _set_cell(cells[3], (evidence[key] or "")[:400])

    _heading(doc, "5.  Regulatory Compliance Assessment", 1)
    doc.add_paragraph(detail.get("compliance_reasoning") or "No compliance reasoning recorded.")

    _heading(doc, "6.  Regulatory Obligations Cited", 1)
    arts = rec.get("articles", []) or []
    if arts:
        ot = doc.add_table(rows=1, cols=3); ot.style = "Table Grid"
        for i, h in enumerate(["Reference", "Framework", "Obligation"]):
            _set_cell(ot.rows[0].cells[i], h, bold=True, colour=RGBColor(0xFF, 0xFF, 0xFF)); _shade(ot.rows[0].cells[i], "2E6B9E")
        for a in arts:
            fw, desc = OBLIGATION.get(a, ("-", "See governing framework text."))
            cells = ot.add_row().cells
            _set_cell(cells[0], a, bold=True); _set_cell(cells[1], fw); _set_cell(cells[2], desc)
    else:
        doc.add_paragraph("No specific obligations were cited for this decision.")

    _heading(doc, "7.  Findings and Rationale", 1)
    for reason in (rec.get("reasons", []) or ["-"]):
        doc.add_paragraph(str(reason), style="List Bullet")

    _heading(doc, "8.  Recommended Action", 1)
    doc.add_paragraph({
        "approve": "Proceed with execution. Continue routine post-execution monitoring and logging.",
        "deny": "Block execution. The request must not proceed. Notify the requesting agent's owner and, where "
                "applicable, remediate the underlying policy violation before resubmission.",
        "human_review": "Hold execution pending human authorisation. Route to a designated reviewer, who must record "
                        "an explicit approve/deny decision before the action may proceed.",
    }.get(decision, "Refer to a governance officer."))

    _heading(doc, "9.  Plain-Language Explanation", 1)
    doc.add_paragraph(explanation or "No explanation generated.")

    _heading(doc, "10.  Audit Trail and Provenance", 1)
    _kv_table(doc, [
        ("Decision timestamp (UTC)", rec.get("decided_at", "-")),
        ("Pipeline", "Intent -> Risk -> Policy retrieval -> Compliance -> Security -> Privacy -> Permission -> Decision"),
        ("Retrieval source", "Hybrid RAG knowledge base (governance_kb)"),
        ("Record integrity (SHA-256, truncated)", digest),
        ("Retention basis", "EU AI Act Art. 12 (record-keeping)"),
    ])

    _heading(doc, "11.  Human Reviewer Sign-Off", 1)
    doc.add_paragraph("To be completed by the designated reviewer where the decision requires human authorisation.")
    st = doc.add_table(rows=0, cols=2); st.style = "Table Grid"
    for label in ["Reviewer name", "Role", "Decision upheld (Yes/No)", "Comments", "Signature", "Date"]:
        cells = st.add_row().cells
        _set_cell(cells[0], label, bold=True); _shade(cells[0], "EAF0F6"); _set_cell(cells[1], "")
    st.columns[0].width = Inches(2.4)

    doc.add_paragraph()
    d = doc.add_paragraph()
    dr = d.add_run("Disclaimer: This report is an automated compliance artefact produced by the Governance Gateway. "
                   "Article and clause references are indicative and should be read against the governing legal texts. "
                   "It does not constitute legal advice.")
    dr.italic = True; dr.font.size = Pt(8); dr.font.color.rgb = GREY

    _footer_pagenum(doc, report_id)
    doc.save(path)
    return report_id


@router.post("/report")
def generate_report(payload: GatewayPayload):
    rec = payload.record or {}
    ts = datetime.datetime.now(datetime.timezone.utc).strftime("%Y%m%d_%H%M%S")
    filename = "governance_report_" + str(rec.get("agent_id","agent")) + "_" + ts + ".docx"
    path = os.path.join(REPORTS_DIR, filename)
    report_id = build_report(rec, payload.explanation or "", path)
    return {"ok": True, "report_id": report_id, "filename": filename,
            "report_path": path, "download_url": "/report/download/" + filename}


@router.get("/report/download/{filename}")
def download_report(filename: str):
    path = os.path.join(REPORTS_DIR, os.path.basename(filename))
    return FileResponse(path, media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                        filename=filename)


@router.post("/audit/log")
def audit_log(payload: GatewayPayload):
    rec = payload.record or {}
    try:
        import psycopg2
        conn = psycopg2.connect(DATABASE_URL)
        cur = conn.cursor()
        cur.execute("CREATE TABLE IF NOT EXISTS gateway_audit (id SERIAL PRIMARY KEY, agent_id TEXT, user_id TEXT, action TEXT, decision TEXT, risk_score INT, risk_tier TEXT, checks JSONB, reasons JSONB, articles JSONB, explanation TEXT, request TEXT, decided_at TIMESTAMPTZ DEFAULT now());")
        cur.execute("INSERT INTO gateway_audit (agent_id,user_id,action,decision,risk_score,risk_tier,checks,reasons,articles,explanation,request) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s) RETURNING id;",
            (rec.get("agent_id"), rec.get("user_id"), rec.get("action"), rec.get("decision"),
             rec.get("risk_score"), rec.get("risk_tier"), json.dumps(rec.get("checks", {})),
             json.dumps(rec.get("reasons", [])), json.dumps(rec.get("articles", [])),
             payload.explanation or "", rec.get("request")))
        new_id = cur.fetchone()[0]
        conn.commit(); cur.close(); conn.close()
        return {"ok": True, "audit_id": new_id}
    except Exception as e:
        return {"ok": False, "error": str(e)}